# configs/dataset/offline_data.yaml
n_points: ${env.num_points}
use_color: ${env.use_color}
workspace_bounds: ${env.workspace_bounds}

# 数据集绝对路径或相对路径
data_path: "/home/luo/.maniskill/demos/${env.env_id}/motionplanning/trajectory.pointcloud.${env.control_mode}.physx_cpu.h5"

# 最大加载的轨迹数（防 OOM），如果不限制则写 null
max_episodes: null
