# configs/train_online.yaml
defaults:
  - model: flow_3d
  - algo: pg              # 在线训练切换为 PG 算法
  - env: maniskill        # 在线训练需要环境 Rollout
  - _self_

run_name: "pg_finetune_flow"
seed: 42
device: "cuda"
epochs: 200
save_dir: "./outputs/online"

wandb:
  enable: true
  project: "RL-100-Infra"