# configs/env/dummy_env.yaml

# 环境名称
env_id: "PickCube-v1"

# 原始环境点云数量 (用于 DummyEnv 测试)
n_original_points: 2048

# 降采样后的点云数量 (传给 PointCloudWrapper)
num_points: 1024

# 是否使用 RGB 颜色特征 (点云为 6 维还是 3 维)
use_color: false

# Action Chunk 的执行步数 (Temporal Ensembling)
exec_steps: 4

# Action Chunk 时序集成的指数衰减权重
exp_weight: 1

workspace_bounds: [[-0.5, -0.5, 0.0], [0.5, 0.5, 0.5]]